### PR TITLE
Set Content-Type header where appropriate

### PR DESCRIPTION
**Pull request by krig**
I wanted to serve .svg documents and Chrome refused to render them
unless the mime type was image/svg+xml, so I added as many mime
types as I could think of while I was at it.

### CODE REVIEW

**Comment by marcomorain** [comment]
LGTM, thanks Kris!

**Comment by marcomorain** [comment]
@krig I just gave you commit access – please keep opening PRs for changes though, so that I can see them :-)

**Comment by krig** [comment]
Haha, cheers! :) Will do.

**Pull request merged**
